### ISSUE TITLE
I recommend https://github.com/abock/dotlang

### ISSUE THREAD

**Issue by PlanetEarthSoftware** [auduchinok/DotParser#20]
Given the number of missing feature bugs I recommend https://github.com/abock/dotlang for parsing GraphVis dot files on .net portably (https://github.com/Rubjerg/Graphviz.NetWrapper uses pre-compiled windows .dlls). Dotlang is low-level relative to DotParser and v0.2.0 but works well.

**Comment by auduchinok** [comment]
@PlanetEarthSoftware Thank you so much for reporting all these issues! They should definitely be fixed, so I'm going to work on them 🙂
