### ISSUE TITLE
Attributes on nodes are dropped when edge attributes exist

### ISSUE THREAD

**Issue by fangyi-zhou** [auduchinok/DotParser#7]
```
digraph G {
compound = true;
a [color=red];
b [color=blue];
a -> b [color=yellow];
}
```
parses into
```
{IsDirected = true;
 IsStrict = false;
 Nodes = map [("a", map []); ("b", map [])];
 Edges = map [(("a", "b"), [map [("color", "yellow")]])];
 GraphAttributes = map [];
 NodeAttributes = map [];
 EdgeAttributes = map [];}
```
where as 
```
digraph G {
compound = true;
a [color=red];
b [color=blue];
}
```
parses into
```
{IsDirected = true;
 IsStrict = false;
 Nodes = map [("a", map [("color", "red")]); ("b", map [("color", "blue")])];
 Edges = map [];
 GraphAttributes = map [];
 NodeAttributes = map [];
 EdgeAttributes = map [];}
```

**Comment by auduchinok** [comment]
Fixed in #8.

**Comment by fangyi-zhou** [comment]
Thanks for accepting the pull request

If you don’t mind, could you make a new release on nuget?

Thanks so much,
Fangyi

— sent from a mobile device, apologies for typos

**Comment by auduchinok** [comment]
@fangyi-zhou I'll be happy to publish an update. I've just managed to restore my NuGet credentials, will try to do it soon.

**Comment by auduchinok** [comment]
@fangyi-zhou Please check 1.1.0 package version.

**Comment by fangyi-zhou** [comment]
Thanks for the update - but I think the dependencies might not be set correctly 

I'm having the following error during execution:
System.IO.FileNotFoundException: Could not load file or assembly 'FSharpx.Core, Version=1.8.41.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

**Comment by fangyi-zhou** [comment]
Workaround:
Add FSharpx.Core to paket.dependencies and paket.reference

**Comment by auduchinok** [comment]
I think it's something from https://github.com/auduchinok/DotParser/pull/3 and https://github.com/auduchinok/DotParser/pull/4, and I haven't released an update after these changes.
Could you open a PR adding the dependency?
